### ISSUE TITLE
Add content to CentOS 7 and 8 installation sections

### ISSUE THREAD

**Issue by peterkaminski** [GovReady/govready-q-docs#1]
These sections of the CentOS 7 and 8 installation instructions do not have examples/instructions:

> 7. Running GovReady-Q with Gunicorn HTTP WSGI
> 8. Monitoring GovReady-Q with Supervisor
> 9. Using NGINX as a reverse proxy

This descends from [PR 906](https://github.com/GovReady/govready-q/pull/906), in which the section headers and preamble for CentOS (just 7, at the time) were copied over from the Ubuntu docs.  The examples/instructions of the sections were not copied, because they needed adaptation from Ubuntu-specific to CentOS-specific, and testing to make sure they were correct.

To resolve this issue, develop, add, and test examples and instructions for these sections for CentOS 7 and 8, using the Ubuntu sections as a starting point.

**Comment by gregelin** [comment]
Completed.
